### ISSUE TITLE
Darstellung von Fehlermeldungen

### ISSUE THREAD

**Issue by monofox** [CVJM-Rhein-Lahn/django-kcevent#15]
Fehlermeldungen werden stellenweise heute wie folgt dargestellt:

![image](https://user-images.githubusercontent.com/765309/108595416-09a8d600-7380-11eb-8880-941901c47666.png)

Wie sollen diese visuell gut für den Nutzer angezeigt werden?

**Comment by monofox** [comment]
Beispiel-Quelltext:

```html
<div class="formgrid-item-full">
        <ul class="errorlist"><li>You must consent to the registration!</li></ul>
        <input type="checkbox" name="reg_consent" class="form-check-input" id="id_reg_consent">
        <label class="form-check-label" for="id_reg_consent">
          Hiermit melde ich mein Kind / mich zu Konfi-Castle im CVJM Kreisverband
          Rhein-Lahn e. V. an. Die Teilnahme ist damit verbindlich.*
        </label>
      </div>
```

**Comment by deniskarbach** [comment]
Ich überlege mir etwas...
Ich denke, wir sollten über Kurz oder Lang zurück zu umrahmten Textfeldern und Boxen kehren. Die könnten dann validiert werden und entsprechend eingefärbt werden.
